//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaXetNghiem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDataContext : DbContext
    {
        public EntityDataContext()
            : base("name=EntityDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BacSi> BacSis { get; set; }
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<KyThuatVien> KyThuatViens { get; set; }
        public virtual DbSet<LoaiXetNghiem> LoaiXetNghiems { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TenXetNghiem> TenXetNghiems { get; set; }
        public virtual DbSet<XetNghiem> XetNghiems { get; set; }
        public virtual DbSet<XetNghiemChiTiet> XetNghiemChiTiets { get; set; }
    }
}
