//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaXetNghiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class XetNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XetNghiem()
        {
            this.XetNghiemChiTiets = new HashSet<XetNghiemChiTiet>();
        }
    
        public System.Guid XetNghiemID { get; set; }
        public Nullable<System.Guid> BenhNhanID { get; set; }
        public Nullable<System.Guid> BacSiID { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> KyThuatVienID { get; set; }
        public Nullable<System.Guid> LoaiXetNghiemID { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual KyThuatVien KyThuatVien { get; set; }
        public virtual LoaiXetNghiem LoaiXetNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XetNghiemChiTiet> XetNghiemChiTiets { get; set; }
    }
}
