//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaXetNghiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class XetNghiemChiTiet
    {
        public System.Guid XetNghiemChiTietID { get; set; }
        public Nullable<System.Guid> XetNghiemID { get; set; }
        public Nullable<decimal> KetQua { get; set; }
        public string KhoangThamChieu { get; set; }
        public Nullable<System.Guid> DonViID { get; set; }
        public Nullable<System.Guid> TenXetNghiemID { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual TenXetNghiem TenXetNghiem { get; set; }
        public virtual XetNghiem XetNghiem { get; set; }
    }
}
